name: deploy to azure

on:
  push:
    branches:
      - master

jobs:
  deploy-azure-app:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Setup nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Install dependencies
      run: |
        dotnet restore
        cd src/Honeydew
        npm install

    - name: publish
      run: |
        cd src/Honeydew
        npm run build:prod
        cd ../../
        dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/honeydew

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'honeydew'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{env.DOTNET_ROOT}}/honeydew 