name: deploy to azure

on:
  push:
    branches:
      - master

jobs:
  deploy-azure-app:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.102'

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/honeydew

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'honeydew'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_918096fcb51d4e9d860bf116f8f0717a }}
        package: ${{env.DOTNET_ROOT}}/honeydew 